sourceURLs:
  - "https://raw.githubusercontent.com/proabiral/Fresh-Resolvers/refs/heads/master/resolvers.txt"
  - "https://raw.githubusercontent.com/blechschmidt/massdns/refs/heads/master/lists/resolvers.txt"
  - "https://raw.githubusercontent.com/trickest/resolvers/refs/heads/main/resolvers.txt"